import type { Metadata } from "next";
import "@/styles/globals.css";
import { geistSans } from "@/styles/fonts/fonts";

export const metadata: Metadata = {
  title: "Ronak Dobariya - Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} bg-background text-foreground antialiased flex flex-col gap-20 relative`}
      >
        {children}
      </body>
    </html>
  );
}
