import type { Metadata } from "next";
import "@/styles/globals.css";
import { geistSans } from "@/styles/fonts/fonts";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Ronak Dobariya - Designer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.className} bg-background text-foreground antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
